import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { MessageCircle, BookOpen, ClipboardList, HelpCircle, Phone, GraduationCap } from "lucide-react";
import { Button } from "@/components/ui/button";
import nsukLogo from "@/assets/nsuk-logo.jpg";
import nsukCampus from "@/assets/nsuk-campus.jpg";
import ReminderCard from "@/components/ReminderCard";

const features = [{ icon: MessageCircle, title: "AI Chat Assistant", desc: "Get instant answers to your admission questions 24/7", link: "/chat" }, { icon: BookOpen, title: "Courses & Faculties", desc: "Explore programs across all faculties and departments", link: "/admission-guide" }, { icon: ClipboardList, title: "Application Guide", desc: "Step-by-step guide through the admission process", link: "/admission-guide" }, { icon: HelpCircle, title: "FAQs", desc: "Find answers to common admission questions", link: "/faqs" }, { icon: Phone, title: "Contact Us", desc: "Reach out to the admission office directly", link: "/contact" }, { icon: GraduationCap, title: "JAMB & Post-UTME", desc: "Requirements, cut-off marks, and registration info", link: "/admission-guide" }];
export default function Index() { return <div className="min-h-screen"><section className="relative py-20 md:py-32 overflow-hidden"><div className="absolute inset-0"><img src={nsukCampus} alt="NSUK Campus" className="w-full h-full object-cover" /><div className="absolute inset-0 hero-overlay" /></div><div className="container mx-auto px-4 relative z-10 text-center"><motion.img initial={{ scale: .8, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} src={nsukLogo} alt="NSUK Logo" className="w-24 h-24 rounded-full bg-primary-foreground/90 object-contain mx-auto mb-6 shadow-xl p-1" /><h1 className="font-display text-3xl md:text-5xl font-bold text-primary-foreground mb-4">NSUK Admission Guide</h1><p className="text-lg text-primary-foreground/80 max-w-2xl mx-auto mb-8">Your AI-powered guide to admission at Nasarawa State University, Keffi.</p><Button asChild size="lg" className="gold-gradient"><Link to="/chat"><MessageCircle className="w-5 h-5 mr-2" />Chat with AI Assistant</Link></Button></div></section><section className="py-16 container mx-auto px-4"><ReminderCard /></section><section className="py-16 container mx-auto px-4"><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl mx-auto">{features.map(({ icon: Icon, title, desc, link }) => <Link key={title} to={link} className="group block p-6 rounded-xl bg-card border border-border hover:shadow-lg transition-all"><div className="w-12 h-12 rounded-xl nsuk-gradient flex items-center justify-center mb-4"><Icon className="w-6 h-6 text-primary-foreground" /></div><h3 className="font-display text-lg font-bold mb-2">{title}</h3><p className="text-sm text-muted-foreground">{desc}</p></Link>)}</div></section></div>; }
